### ISSUE TITLE
error in geomap

### ISSUE THREAD

**Issue by gusunavarro** [biolab/orange3-geo#114]
Hello

Iam new in orange. I install under anaconda, but when I activate the orange3-geo
I have these error
I have version 3.2.3 and install under anaconda.
I use Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 

Traceback (most recent call last):
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangecanvas/scheme/widgetmanager.py", line 371, in __process_init_queue
    self.ensure_created(node)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangecanvas/scheme/widgetmanager.py", line 320, in ensure_created
    self.__add_widget_for_node(node)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 408, in create_widget_instance
    widget.__init__()
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangecontrib/geo/widgets/owmap.py", line 130, in __init__
    super().__init__()
  File "/home/gus/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/utils/widget.py", line 397, in __init__
    self.setup_gui()
  File "/home/gus/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/utils/widget.py", line 402, in setup_gui
    self._add_controls()
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangecontrib/geo/widgets/owmap.py", line 157, in _add_controls
    searchable=True)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/Orange/widgets/gui.py", line 581, in comboBox
    miscellanea(combo, hb, widget, **misc)
  File "/home/gus/anaconda3/lib/python3.7/site-packages/orangewidget/gui.py", line 232, in miscellanea
    getattr(control, "set" + prop[0].upper() + prop[1:])(val)
AttributeError: 'ComboBox' object has no attribute 'setSearchable'

thanks
gus

**Comment by gusunavarro** [comment]
Hello
Today  I install the new version 3.26 and now is all ok.
