### ISSUE TITLE
Error when renaming countries

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3-geo#117]
##### Geo version

0.2.8

##### Orange version

3.27.1

##### Expected behavior
I have a dataset which uses different names for some countries than expected by orange3-geo, which results in “Unmatched identifiers”.  I rename these, and I expect this renaming to work without errors.  If the data entered is somehow incorrect I expect a more relevant error message telling me what I should do instead.

##### Actual behavior
For each country I rename I get a popup window with the following contents:

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/utils/sql.py", line 31, in new_f
    return f(widget, data, *args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/visualize/utils/widget.py", line 448, in set_data
    effective_data = self.effective_data if data_existed else None
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/visualize/utils/widget.py", line 441, in effective_data
    self.data.domain.metas))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/data/domain.py", line 154, in __init__
    raise Exception('All variables in the domain should have'
Exception: All variables in the domain should have unique names.

##### Steps to reproduce the behavior
Read the attached data file with File, connect to Geocoding.  Open the Geocoding widget, fill in Custom Replacements for Unmatched identifiers.

##### Additional info (worksheets, data, screenshots, ...)
[gdppercapita_us_inflation_adjusted.xlsx](https://github.com/biolab/orange3-geo/files/5661620/gdppercapita_us_inflation_adjusted.xlsx)

<img width="660" alt="Screenshot 2020-12-08 at 20 52 36" src="https://user-images.githubusercontent.com/10616212/101535593-2ba5d580-3999-11eb-8a67-aebf8f9d28d0.png">

<img width="664" alt="Screenshot 2020-12-08 at 20 52 50" src="https://user-images.githubusercontent.com/10616212/101535618-33fe1080-3999-11eb-8ba7-5327a25021c7.png">

**Comment by VesnaT** [comment]
@kaimikael I can not reproduce the error. I think it has already been fixed. The fixed version will be available with the next release.

**Comment by ajdapretnar** [comment]
This is likely resolved. If the issue persist with the new version of Orange (3.28.0), please reopen.

**Comment by kaimikael** [comment]
Still there I’m afraid.  Orange sent on an automatic error report to you as well.

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1010, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1048, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 679, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/utils/sql.py", line 31, in new_f
    return f(widget, data, *args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/utils/widget.py", line 450, in set_data
    effective_data = self.effective_data if data_existed else None
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/utils/widget.py", line 441, in effective_data
    return self.data.transform(Domain(self.effective_variables,
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/data/domain.py", line 153, in __init__
    raise Exception('All variables in the domain should have'
Exception: All variables in the domain should have unique names.
<img width="1408" alt="Screenshot 2021-03-26 at 11 29 09" src="https://user-images.githubusercontent.com/10616212/112618731-be725f00-8e26-11eb-8a6b-89e9ccdad1a0.png">

**Comment by ajdapretnar** [comment]
I'm afraid I still can't reproduce. Tried this on Orange 3.28.0 (dmg) with the latest version of Geo. No errors appear.

**Comment by kaimikael** [comment]
Hah!  It turned out to be one of those things where old settings remained even though I created a new workflow.  Resetting the widgets solved the issue.

**Comment by ajdapretnar** [comment]
🤔 So in a way that you set the workflow in one version and in a newer version the old settings caused an issue even though they shouldn't (recreating the same workflow with cleared settings works)? @markotoplak Is this something we should worry about?

**Comment by kaimikael** [comment]
So it seems.  So this would be another case in which https://github.com/biolab/orange3/issues/5205 bit me.
