### ISSUE TITLE
Error using Geocoding widget

### ISSUE THREAD

**Issue by rehoyt** [biolab/orange3-geo#152]
Perhaps a year ago I was able to connect a dataset of patients with lat/longs and create a geo map of their location. 
Now when I try to do this I get an error message. I am now using Orange version 3.33 on My Mac Monterey OS 12.6

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/geo/widgets/owgeocoding.py", line 155, in __init__
    view.horizontalHeader().setResizeMode(QHeaderView.Stretch)
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'

**Comment by janezd** [comment]
Thanks for the report. It was a trivial problem that should had been detected by automated testing, but wasn't due to old configuration.

I guess we'll need an urgent release of the add-on. If this widget fails, the add-on is nearly useless.
