### ISSUE TITLE
Geocoding crashes

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-geo#172]
##### Geo version
0.4.0

##### Orange version
3.36.2

##### Expected behavior
It should be possible to input data to Geocoding

##### Actual behavior
When connecting any input to it, Geocoding crashes with the following error report:
```
Traceback (most recent call last):
  File "/Applications/Orange.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangecanvas/scheme/widgetmanager.py", line 243, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "/Applications/Orange.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "/Applications/Orange.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "/Applications/Orange.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangecontrib/geo/widgets/owgeocoding.py", line 163, in __init__
    view.verticalHeader().setSectionResizeMode(0)
TypeError: arguments did not match any overloaded call:
  setSectionResizeMode(self, logicalIndex: int, mode: QHeaderView.ResizeMode): not enough arguments
  setSectionResizeMode(self, mode: QHeaderView.ResizeMode): argument 1 has unexpected type 'int'
```
It isn't possible at all to apply Geocoding.

##### Steps to reproduce the behavior
[geocoding crash.ows.zip](https://github.com/biolab/orange3-geo/files/13820338/geocoding.crash.ows.zip)

**Comment by janezd** [comment]
This PyQt6 incompatibility has been fixed in #169 almost a year ago, but we haven't made any releases since then because there hasn't been much new.

I guess it's time for a patch release. Any volunteers?

(I could do it, but it would take me much longer because I don't do it often and I'm too old to remember the procedure.)

**Comment by PrimozGodec** [comment]
I can make a release tomorrow morning.

**Comment by PrimozGodec** [comment]
The addon is now released on all platforms, so please upgrade the addon to the newest version 0.4.1. :)

**Comment by wvdvegte** [comment]
I can confirm that it no longer crashes!
