### ISSUE TITLE
Geocoding: concatenation error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#81]
##### Geo version

latest

##### Orange version

3.23.0

##### Expected behavior
Geocoding works.

##### Actual behavior
Geocoding crashes.

##### Steps to reproduce the behavior
Datasets (Cyber Security Breaches) - Geocoding. Set the Region Identifier to US State.

##### Additional info (worksheets, data, screenshots, ...)
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1737, in __call__
    self.func(**kwds)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owgeocoding.py", line 216, in region_attr_changed
    self.commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1524, in unconditional_commit
    do_commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1532, in do_commit
    commit()
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owgeocoding.py", line 223, in commit
    output = self.data.concatenate((self.data, output))
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 853, in concatenate
    raise ValueError('concatenated tables must have the same domain')
ValueError: concatenated tables must have the same domain
```

**Comment by anamilkochar** [comment]
hi, i am facing the same error when i try to run seasonal adjustment widget on a time series data. Please help on the same. 

error below: 


Exception:
ValueError: concatenated tables must have the same domain
Module:
Orange.data.table:881
Widget Name:
Seasonal Adjustment
Widget Module:
orangecontrib.timeseries.widgets.owseasonaladjustment:124
Widget Scheme:
C:\Users\ADMIN\AppData\Local\Temp\ows-_lh5jpe0.ows.xml
Version:
3.24.1
Environment:
Python 3.6.10 on Windows 10 10.0.17763 AMD64
Installed Packages:
AnyQt==0.0.10, Bottleneck==1.2.1, CacheControl==0.12.5, Orange3-Timeseries==0.3.4, Orange3==3.24.1, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyYAML==5.2, XlsxWriter==1.2.7, asn1crypto==1.3.0, certifi==2019.11.28, cffi==1.13.2, chardet==3.0.4, commonmark==0.9.1, cryptography==2.8, cycler==0.10.0, decorator==4.4.1, docutils==0.15.2, entrypoints==0.3, et-xmlfile==1.0.1, future==0.18.2, idna==2.8, importlib-metadata==1.3.0, jdcal==1.4.1, joblib==0.14.1, keyring==20.0.0, keyrings.alt==3.1.1, kiwisolver==1.1.0, llvmlite==0.31.0, lockfile==0.12.2, lxml==4.5.0, matplotlib==2.2.2, mkl-fft==1.0.15, mkl-random==1.1.0, mkl-service==2.3.0, more-itertools==8.0.2, msgpack==0.6.1, networkx==2.4, numba==0.47.0, numpy==1.16.5, openTSNE==0.3.11, openpyxl==3.0.2, orange-canvas-core==0.1.11, orange-widget-base==4.3.0, pandas-datareader==0.8.1, pandas==0.25.3, patsy==0.5.1, pip==19.3.1, pyOpenSSL==19.1.0, pycparser==2.19, pynndescent==0.3.3, pyparsing==2.4.6, pyqtgraph==0.10.0, python-dateutil==2.8.1, python-louvain==0.13, pytz==2019.3, pywin32-ctypes==0.2.0, requests==2.22.0, scikit-learn==0.22.1, scipy==1.2.1, serverfiles==0.3.0, setuptools==44.0.0.post20200106, six==1.13.0, statsmodels==0.11.1, tornado==6.0.3, urllib3==1.25.7, wheel==0.33.6, win-inet-pton==1.1.0, wincertstore==0.2, xlrd==1.2.0, zipp==0.6.0
Machine ID:
89abc96a-0346-4793-9516-4e5277bb3ce0
Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py", line 1579, in do_commit
    commit()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owseasonaladjustment.py", line 124, in commit
    ts = Timeseries(Timeseries.concatenate((data, adjusted_data)))
  File "C:\Program Files\Orange\lib\site-packages\Orange\data\table.py", line 881, in concatenate
    raise ValueError('concatenated tables must have the same domain')
ValueError: concatenated tables must have the same domain

Local Variables:
OrderedDict([('axis', 0),
             ('cls', <class 'orangecontrib.timeseries.timeseries.Timeseries'>),
             ('collect',
              <function Table.concatenate.<locals>.collect at 0x0000024259B64510>),
             ('domain',
              [TOTAL_SALES, ROA, EBITDA_MARGIN_PCT, NET_DEBT_TO_EBITDA, EBITDA_TO_INTEREST_EXPENSE, FFO_CASH_TO_DEBT_ST, CASH_CONV_CYCLE | ROE] {ENTITY_NAME, factset_entity_id, FISCAL_PERIOD_END_DATE}),
             ('merge1d',
              <function Table.concatenate.<locals>.merge1d at 0x0000024258E3EE18>),
             ('tables',
              ([[917.3, 7.03964, 75.1118, 1.5486, 7.7081, ... | 12.433] {TransAlta Corp., 003FXF-E, 1987-12-31 00:00:00},
 [962.1, 6.1998, 73.6722, 1.97997, 6.17422, ... | 11.0646] {TransAlta Corp., 003FXF-E, 1988-12-31 00:00:00},
 [969.6, 5.00529, 65.3465, 2.41951, 3.87523, ... | 9.93365] {TransAlta Corp., 003FXF-E, 1989-12-31 00:00:00},
 [1063.5, 3.76186, 61.0813, 2.47183, 3.68254, ... | 7.79444] {TransAlta Corp., 003FXF-E, 1990-12-31 00:00:00},
 [1160.6, 4.05056, 57.2893, 2.31057, 3.94834, ... | 8.242] {TransAlta Corp., 003FXF-E, 1991-12-31 00:00:00},
 ...
],
               [[8.03611, -0.328008, 5.14825, 2.88786],
 [5.99307, 0.181142, 5.07574, 0.917336],
 [3.02997, 0.845256, 5.00323, -1.97326],
 [3.31182, 0.370722, 4.93072, -1.6189],
 [2.69157, 1.25676, 4.85821, -2.16664],
 ...
])),
             ('vstack',
              <function Table.concatenate.<locals>.vstack at 0x000002426119A268>)])

thanks
