### ISSUE TITLE
Geocoding: does not work on master

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#88]
##### Geo version

0.2.6

##### Orange version

3.24.dev

##### Expected behavior
Geocoding works.

##### Actual behavior
Geocoding stalls indefinitely.

##### Steps to reproduce the behavior
File - Geocoding.

##### Additional info (worksheets, data, screenshots, ...)
I am also getting a Shapely error, but I am not sure this is the problem.

```
Traceback (most recent call last):
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/mapper.py", line 132, in init
    points.append([poly.centroid.y, poly.centroid.x])
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/site-packages/shapely/geometry/base.py", line 471, in centroid
    return geom_factory(self.impl['centroid'](self))
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/site-packages/shapely/topology.py", line 77, in __call__
    self._validate(this)
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/site-packages/shapely/topology.py", line 18, in _validate
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations
```

**Comment by robertcv** [comment]
Cannot reproduce
